version: "3"
services:
    bludit2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bludit2
        ports:
            - "8000:80"
        restart: always
        stdin_open: true
        tty: true
    config2:
        build:
            context: .
            dockerfile: Dockerfile_config
        container_name: config2
        depends_on:
            - bludit2
    poc2:
        build:
            context: .
            dockerfile: Dockerfile_poc
        container_name: poc2
        ports:
            - "8080:80"
        depends_on:
            - bludit2   
            - config2   
