version: "3"
services:
    bludit:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bludit
        ports:
            - "8000:80"
        restart: always
        stdin_open: true
        tty: true
    config:
        build:
            context: .
            dockerfile: Dockerfile_config
        container_name: config
        depends_on:
            - bludit
    poc:
        build:
            context: .
            dockerfile: Dockerfile_poc
        container_name: poc
        ports:
            - "8080:80"
        depends_on:
            - bludit 
            - config 
